# NumPy

## Introduction

- NumPy is a general-purpose array-processing package
- Travis Oliphant First Released in 1995 (Released as __Numeric__; Changed to NumPy in 2006). It is written in Python and C
- NumPy is cross-platform and BSD-licensed. Often used with packages such as Matplotlib (plotting library) and SciPy (Scientific Python). Sometimes it is seen as an alternative to MATLAB. The term ‘Numpy’ is a portmanteau of the words ‘NUMerical’ and ‘PYthon
- It is a library that allows end-users to create **high-performance multidimensional array objects** and manipulate these arrays (objects)
- NumPy provides a gamut of high-level functions for mathematical and logical operations, Fourier transforms, array shape manipulations, linear algebra operations, random number generation, etc.

### Examples of Multi-dimensional Arrays

* Values of an experiment/simulation at discrete time steps.
* Signal recorded by a measurement device, e.g. sound wave.
* Pixels of an image, grey-level or colour.
* 3D data measured at different X-Y-Z positions, e.g. MRI scan.
* ...

The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype).

Any item extracted from ndarray object (by slicing) is represented by a Python object of one of array scalar types.
<p><b>The above constructor takes the following parameters −<b></p>

<table>
    <tr>
        <th>Sr.No.</th>
        <th>Parameter & Description</th>
    <tr>
    <tr>
        <td>1. object</td>
        <td>Any object exposing the array interface method returns an array, or any (nested) sequence.</td>
    </tr>
    <tr>
        <td>2. dtype</td>
        <td>Desired data type of array, optional</td>
    </tr>
    <tr>
        <td>3. copy</td>
        <td>Optional. By default (true), the object is copied</td>
    </tr>
    <tr>
        <td>4. order</td>
        <td>C (row major) or F (column major) or A (any) (default)</td>
    </tr>
    <tr>
        <td>5. subok</td>
        <td>By default, returned array forced to be a base class array. If true, sub-classes passed through</td>
    </tr>
    <tr>
        <td>6. ndmin</td>
        <td>Specifies minimum dimensions of resultant array</td>
    </tr>
</table>

## Numpy Installation

Once you have installed `pip`, i.e., the default python package manager; installing numpy is straightforward.

`pip install numpy`

## Numpy Import

Conventionally, numpy is imported as `np` as shown below

In [1]:
import numpy as np
print(np.__version__)    # Check the numpy version

1.16.4


## Basic Usage

In [3]:
# Create a 3 x 3 array, with all elements initialized to 1. Default data type for array is float.
b = np.ones((3, 3))
print(b)
type(b)    # print datatype of b
b.dtype    # print datatype of elements in b

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


dtype('float64')

In [8]:
# Modify the data type of array elements
c = np.ones((3, 4), dtype=int)
print(c)
type(c)
c.dtype

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


dtype('int64')

In [ ]:
d = np.array([11 + 12j, 13 + 14j, 15 + 16j])    # numpy array with complex data type
d.dtype

In [ ]:
e = np.array([False, True, True, False, False, True])    # numpy array with complex data type 
e.dtype

In [5]:
f = np.array(['Welcome', 'To', 'Numpy'])
f.dtype    # Unicode string of 7 characters

dtype('<U7')

In [10]:
len(c[0])    # get the length of the array

4

In [11]:
c.shape

(3, 4)

In [7]:
# Shortcut to create an array of numbers
ar = np.arange(5)
print(ar)

[0 1 2 3 4]


In [9]:
# Indexing on 1-D array - This is similar to Python lists
ar[1], ar[3], ar[-1]

(1, 3, 4)

In [8]:
# Arrays are assigned by reference

a = np.array([10, 11, 12, 13]) # create array
print(a)       # print a's value
print(type(a)) # type of variable a 
print(id(a))

b = a    # reference assignment
print(id(b))
b[0] = 20
print(a[0])

[10 11 12 13]
<class 'numpy.ndarray'>
2883611510544
2883611510544
20


## How to Get Help?

We encourage you to refer to the help, as often as possible. As it provides in-depth explanation of the functions, its usage and internals. This will help you build better intuition of what's happening behind the scenes. And often, you will need to tweak the arguments to function, specially when dealing with large datasets, to achieve good performance.

In [ ]:
help(np.array) # About numpy array

In [ ]:
help('array')  # BTW this is the built-in array and not numpy array

In [ ]:
np.lookfor('array create') # If exact name is not known, search for the topic

In [ ]:
help(np.zeros) # About zeros

## NumPy Multi-dimensional Arrays (ndarray)
This is one of the most important features of numpy. ndarray is an n-dimensional array, a grid of values of the same data type. To index into this array we have a tuple of nonnegative integers.

In [17]:
# Create a 2-D matrix, with 2 rows and 3 columns
b = np.array([[1, 2, 3], [4, 5, 6]])
print("A 2-D matrix")
print(b)
print("Dimensions:", b.ndim)  # Number of dimensions, 2 (i.e. rows and columns)
print("Shape:", b.shape) # Number of elements in each dimension, i.e. number of rows and number of columns
print("Rows:", len(b))  # Number of rows
print("Cols:", len(b[0])) # Number of columns
print("==========")
# Creat a 3-D array, with dimensions 2 x 2 x 2. Consider this as a stack of 2 matrices of dimensions 2 x 2
c = np.array([
    [[1, 2], [3, 4]],    # Matrix of dimension 2 x 2
    [[1, 1], [2, 2]]     # Matrix of dimension 2 x 2
    ])
print("A 3-D matrix")
print(c)
print("Dimensions:", c.ndim)
print("Shape:", c.shape)

A 2-D matrix
[[1 2 3]
 [4 5 6]]
Dimensions: 2
Shape: (2, 3)
Rows: 2
Cols: 3
A 3-D matrix
[[[1 2]
  [3 4]]

 [[1 1]
  [2 2]]]
Dimensions: 3
Shape: (2, 2, 2)


## Indexing and slicing

Indexes are tuples of numbers

In [83]:
a = np.diag(np.arange(3))   # create a 3 by 3 array with diagonal elements set to 0, 1, 2
print(a)
a[1, 1]    # Indexing starts with 0. Here we are slicing one element in the second row and second column. We used a tuple 1, 1

[[0 0 0]
 [0 1 0]
 [0 0 2]]


1

In [21]:
a[2, 1] = 10 # Update array element
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [84]:
print(a[1:, 0:2])  # We can use slicing concepts for all the dimensions!

[[0 1]
 [0 0]]


In [24]:
ar = np.arange(10)
print(ar)
ar[:4]    # Slice, starting from zero and ending at three

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3])

In [25]:
ar[::2]    # Slice every second element, starting from 0

array([0, 2, 4, 6, 8])

## Transpose

In [2]:
import numpy as np
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Permute the dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : list of ints, optional
        By default, reverse the dimensions, otherwise permute the axes
        according to the values given.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the `axes` keyword argument.
    
    Transposing a 1-D array returns an unchanged view of the original array.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.transpose(x)
    array([[0, 2],
           [1, 3]])
    
    >>> x = np.ones((1, 2, 3))
    >>> np.transpose(x, (1, 0, 2)).s

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array shape:", arr.shape)
print(arr)
arr_transp = np.transpose(arr)
print("Transpose array shape:", arr_transp.shape)
print(arr_transp)
# + np.transpose([np.arange(0, 51, 10)])

Array shape: (2, 3)
[[1 2 3]
 [4 5 6]]
Transpose array shape: (3, 2)
[[1 4]
 [2 5]
 [3 6]]


## Updating Array Values

In [4]:
arr[1][1] = 2
print(arr)    # value 5 is updated by 2

arr_transp[1, 1] = 2  # value 5 updated by 2
print(arr_transp)

[[1 2 3]
 [4 2 6]]
[[1 4]
 [2 2]
 [3 6]]


## Total Number of Elements in the Array

In [40]:
import numpy as np 
help(np.size)

Help on function size in module numpy:

size(a, axis=None)
    Return the number of elements along a given axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : int, optional
        Axis along which the elements are counted.  By default, give
        the total number of elements.
    
    Returns
    -------
    element_count : int
        Number of elements along the specified axis.
    
    See Also
    --------
    shape : dimensions of array
    ndarray.shape : dimensions of array
    ndarray.size : number of elements in array
    
    Examples
    --------
    >>> a = np.array([[1,2,3],[4,5,6]])
    >>> np.size(a)
    6
    >>> np.size(a,1)
    3
    >>> np.size(a,0)
    2



In [5]:
arr.size 

6

In [6]:
arr.shape

(2, 3)

## Array of Random Numbers

In [ ]:
import numpy as np
help(np.random.random)

In [41]:
nr = np.random.random((3, 3)) # 2 dimensional array of 3 rows and 3 columns with random numbers 
# Elements in array are randomly generated using the random function.
print(nr)      

[[0.63776061 0.49415294 0.11265457]
 [0.31666149 0.74793493 0.59006333]
 [0.58650475 0.12931283 0.40211594]]


In [ ]:
# TRY THIS OUT!
# a = np.random.random((1000, 1000))  # It will create an array of size 1k by 1k with random values inside it 
# print(a)

## Array Functions

### `np.ones()`

Returns a new array of given shape and data type, where all the elements are set to 1.

`ones(shape, dtype=None, order='C')`

The shape is an int or tuple of ints to define the size of the array. If we just specify an int variable, a one-dimensional array will be returned. For a tuple of ints, the array of given shape will be returned.<br>
The dtype is an optional parameter with default value as a float. It’s used to specify the data type of the array, for example, int. <br>
The order defines the whether to store multi-dimensional array in row-major (C-style) or column-major (Fortran-style) order in memory.

In [ ]:
help(np.ones)

In [43]:
c = np.ones((3, 2))
print(c)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


### `np.zeros()`

It is identical to `np.ones()`, except that all the elements are initialized to zero.

In [ ]:
import numpy as np
help(np.zeros)

In [44]:
d = np.zeros((2, 3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


### `np.eye()`

Returns an array where all the elements are equal to zero, except diagonal elements that are initialized to 1.

In [ ]:
import numpy as np
help(np.eye)

In [45]:
e = np.eye((3))  # This creates the popularly known Identity Matrix!
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
# Different dimensions of arrays created with np.eye
print(np.eye(5))
print()
print(np.eye(2,3))
print()
print(np.eye(3,3))
print()
print(np.eye(4, k=-3))
print()
print(np.eye(5, k=2))
print()
print(np.eye(2, 3))
print()
print(np.eye(5, dtype=int))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]]

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### `full()`
Returns a new array with the same shape and type as a given, filled with the fill_value.
    
Syntax:

`full(shape, fill_value, dtype = None, order = 'C')`

In [ ]:
help(np.full)

In [49]:
e = np.full((5, 4), 7) # Matrix of constant numbers
print(e)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


### `np.linspace()`

Returns number spaces evenly w.r.t the given interval start and stop. This functions is similar to arange but instead of step size it uses a sample number.

Syntax:

`numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None)

In [ ]:
import numpy as np 
help(np.linspace)

In [50]:
f = np.linspace(1, 10, 4) # Generate 4 equally spaced values between 1 and 10
print(f)

[ 1.  4.  7. 10.]


In [52]:
# Sample other variations of linspace
print(np.linspace(1, 2, retstep=True))
print()
print(np.linspace(1, 100, num=5, retstep=True))
print()
a = np.linspace(1, 100, num=5, endpoint=False, retstep=True)
print(a)
print(a[0][0])
np.linspace(1, 100, num=5, retstep=True)
np.linspace(1, 100, num=5, dtype=int)

(array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ]), 0.02040816326530612)

(array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ]), 24.75)

(array([ 1. , 20.8, 40.6, 60.4, 80.2]), 19.8)
1.0


array([  1,  25,  50,  75, 100])

### `np.empty()`

Return a new array of given shape and type, without initializing entries.

In [ ]:
import numpy as np
help(np.empty)

In [57]:
# empty, unlike zeros,it does not set the array values to zero
g1 = np.empty([2, 2], dtype=int) # Creates an empty array 
print(g1)

[[         0 1072693248]
 [         0 1072693248]]


### Minimum Dimensions

Specifies minimum dimensions of the resultant array

In [60]:
h = np.array([1, 2, 3], ndmin=3) # ndmin provides minimum dimension
print(h)
print(h.ndim)
h = np.array([1, 2, 3]) # ndmin provides minimum dimension
print(h)
print(h.ndim)

[[[1 2 3]]]
3
[1 2 3]
1


### Complex Datatype 

In [62]:
i = np.array([1, 3, 4], dtype=complex) # It creates the array with the complex values.
print(i)
i = np.array([1, 3, 4]) # If datatype is not provided then numpy decides the datatype for us.
print(i)

[1.+0.j 3.+0.j 4.+0.j]
[1 3 4]


### reshape()

In [ ]:
import numpy as np
help(np.reshape)

In [64]:
j = np.array([[1, 2, 3], [4, 5, 6]])
print(j)
print(j.reshape(3,2)) # It will change the shape of the array with 3 rows and two columns

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


### Creating a Row or Column Vector

In [66]:
vec_row = np.array([1, 2, 3])
vec_col = np.array([[4], [5], [6]])
print("Row vector: ", vec_row)
print("Column vector ", vec_col)

Row vector:  [1 2 3]
Column vector  [[4]
 [5]
 [6]]


### Create a Matrix with `np.mat()`

In [ ]:
help(np.mat)

In [70]:
matrix = np.array([[1,2],[3,4],[5,6]])
print(matrix)
print(type(matrix))

matrix = np.mat([[1,2],[3,4],[5,6]])
print(matrix)
print(type(matrix))

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.matrix'>


### Creating a Sparse Matrix

For many problems with large datasets, we may have to create sparse matrices, where a lot of element values are missing (not available).

In [71]:
from scipy import sparse
matrix = np.mat([[1,1],[2,2],[3,3]])
print(matrix)

sparse_matrix = sparse.csr_matrix(matrix) # It is a compressed Sparse matrix 
print(sparse_matrix) # The output will have the position of the element and the element too

[[1 1]
 [2 2]
 [3 3]]
  (0, 0)	1
  (0, 1)	1
  (1, 0)	2
  (1, 1)	2
  (2, 0)	3
  (2, 1)	3


## Copies and Views

* Slicing creates a *view*, not a copy
* Modifying a view also modifies the original
* You can force a copy with `.copy()`

In [7]:
a = np.arange(10)
b = a[::2]    # This is a view
a, b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 2, 4, 6, 8]))

In [76]:
b[0] = 14    # Modify the view and the original also gets affected
a, b

(array([14,  1,  2,  3,  4,  5,  6,  7,  8,  9]), array([14,  2,  4,  6,  8]))

In [77]:
a = np.arange(10)
b = a[::2].copy()  # This creates a new copy of the array
b[0] = 14          # This update doesn't impact the original
a, b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([14,  2,  4,  6,  8]))

### Conditional and Logical Selection

In [79]:
# Conditional and Logical selection 
ar = [[34, 23, 56, 78], [76, 98, 6, 3], [23, 54, 77, 45]]
ar = np.array(ar)
ar > 60 # Compares each element in the array with the number 60 and returns true / false

array([[False, False, False,  True],
       [ True,  True, False, False],
       [False, False,  True, False]])

In [81]:
# The good part is that we can use the above result and get the elements that are > 60
print(ar[(ar > 60)])    # Get all the values that are greater than 60

print(ar[(ar > 30) & (ar < 60)])    # We can have logical operations to generate index of elements to retrieve from the array

[78 76 98 77]
[34 56 54 45]


In [90]:
# Broadcasting: to change multiple elements at once
arr3 = np.array([[23, 54, 65, 77]])
print(arr3)
arr3[:1,:3] = 40
print(arr3)

[[23 54 65 77]]
[[40 40 40 77]]


## Operations on Matrix Elements

In [93]:
matrix = np.mat([[1, 2, 3], [3, 4, 2], [4, 4, 6]])
add_100 = lambda i: i + 100
vectorized_mat = np.vectorize(add_100) # create a vectorize variable
vectorized_mat(matrix) # Apply the vectorization effect on the defined matrix

matrix([[101, 102, 103],
        [103, 104, 102],
        [104, 104, 106]])

### Finding Maximum and Minimum Values


In [94]:
matrix = np.mat([[1, 2, 3], [3, 5, 4], [9, 8, 7]])
print("Max:", np.max(matrix))    # Returns the maximum element of the matrix
print("Min:", np.min(matrix))    # Returns the minimum elemnt of the matrix

Max: 9
Min: 1


### Applying Operations along a Specific Axis
Using the axis parameter we can also apply the operation along a certain axis:<br>
axis=0 means on each column <br>
axis=1 means on each row

In [95]:
matrix = np.mat([[1, 2, 3], [0, 1, 2], [3, 0, 2]])
print(matrix)
print("Max (axis=0):", np.max(matrix, axis=0))# Returns the maximum element of each row
print("Max (axis=1):", np.max(matrix, axis=1))

[[1 2 3]
 [0 1 2]
 [3 0 2]]
Max (axis=0): [[3 2 3]]
Max (axis=1): [[3]
 [2]
 [3]]


### Calculating Average Variance and Standard Deviation 

In [ ]:
import numpy as np
matrix=np.array([[1,2,3],[6,4,5],[8,9,7]])
print("The mean of the matrix is :" ,np.mean(matrix))# It will give the mean of the matrix
print()
print("The variance of the matrix is :" ,np.var(matrix))# It will give the variance of the matrix
print()
print("The standard deviation of the matrix is :" ,np.std(matrix))# It will give the standard Deviation of the matrix

### Reshaping of the arrays or matrix

In [ ]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(matrix.reshape(6,2))# Change the shape of the matrix
print()
print(matrix.reshape(2,6))# Change the shape of the matrix
print()
print(matrix.reshape(1, -1))# Change it to 2 D row array
print()
print(matrix.reshape(12))# provides a row array of 1 D

### Transposing a vector or matrix

In [1]:
import numpy as np 
matr=np.array([[1,2,3],[3,4,5],[6,8,9]])
print("The original Matrix is :\n", matr)
print()
print("The Transposed Matrix is :\n",matr.T)
print()

The original Matrix is :
 [[1 2 3]
 [3 4 5]
 [6 8 9]]

The Transposed Matrix is :
 [[1 3 6]
 [2 4 8]
 [3 5 9]]



In [2]:
import numpy as np
def numpysum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c
print(numpysum(10))

[  0   2  12  36  80 150 252 392 576 810]


In [ ]:
import numpy as np
myarray=np.mat([[1,2,3,4],[4,3,2,1]],dtype=np.int64)
print(myarray)

#### To create a np arrays using lists

In [ ]:
import numpy as np
alist=["a","Ram",8] # Define a list 
arr=np.array(alist) # conver a list to array
print(arr)# print the array
print(arr.dtype)# prints the data type for more information refer numpy documentation
print(arr.ndim) # Provides the dimension of the array
print(arr.shape)# if it is 1 D then you will just get the number of values as a tuple

#### To create a Matrix

In [ ]:
arr_l=[[[1,2,3],[4,5,6],[7,8,9]],[[1,1,1],[3,3,3],[2,1,5]]]# Define a list of values 
matr=np.array(arr_l) # convert it into matrix 
#print(arr_l)
print(matr)# print matrix
#matr
print(matr.dtype)# print the data type of matrix
#matr.dtype
print(matr.ndim) # print the dimension of matrix
#matr.ndim
print(matr.shape) # print the shape of matrix
#matr.shape

In [ ]:
a_list=[["x"],{"name:Ram"}] 
arr=np.array(a_list)
print(arr.dtype)
print(arr.shape)

In [ ]:
import numpy as np 
arr6=np.random.randint(2,8,(2,4,7))
print(arr6)

**numpy.random.randn()** in Python

**About:** numpy.random.randn(d0, d1, …, dn) : creates an array of specified shape and fills it with random values as per standard normal distribution.

If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.


In [3]:
import numpy as np 
arr7=np.random.randn(6)
print(arr7)

[-0.3451395  -0.71242982  0.74466962  1.28256678 -1.20647668  1.4477153 ]


In [4]:
import numpy as np 
arr8 =np.random.randn(3,2)
print(arr8)

[[ 0.17335107 -0.42103373]
 [ 0.0772516   0.1636836 ]
 [-0.34495371 -1.63530379]]


In [ ]:
import numpy as np 
arr9=np.random.randn(2,4,4)
print(arr9)
print()
arr10=np.random.randn(2,4,4)*2+3
print(arr10)

In [5]:
a=np.array([1,2,3],float)
b=a
c=a.copy()
a[0]=0
print(a)
print(b)
print(c)

[0. 2. 3.]
[0. 2. 3.]
[1. 2. 3.]


In [6]:
import numpy as np 
b=np.array([1,2,3],float)
print(b)
b.fill(0)
print(b)

[1. 2. 3.]
[0. 0. 0.]


In [7]:
a=np.array(range(6),float).reshape((2,3))
print(a)
a.transpose()

[[0. 1. 2.]
 [3. 4. 5.]]


array([[0., 3.],
       [1., 4.],
       [2., 5.]])

### One-dimensional versions of multi-dimensional arrays can be generated with flatten:

In [ ]:
b=np.array([[1,2,3],[4,5,6]],float)
print(b)
print(b.flatten())

### Two or more arrays can be concatenated together using the concatenate function with a tuple of the arrays to be joined:

In [8]:
a=np.array([1,2],float)
b=np.array([3,4,5,6],float)
c=np.array([7,8,9],float)
np.concatenate((a,b,c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
a=np.array([[1,2],[3,4]],float)
b=np.array([[5,6],[8,0]],float)
print(np.concatenate((a,b)))
print()
print(np.concatenate((a,b),axis=0))
print()
print(np.concatenate((a,b),axis=1))

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [8. 0.]]

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [8. 0.]]

[[1. 2. 5. 6.]
 [3. 4. 8. 0.]]


### Finally, the dimensionality of an array can be increased using the newaxis constant in bracket notation:

In [ ]:
a=np.array([1,2,3],float)
print(a)
print()
print()
print(a[:,np.newaxis])
print()
print()
print(a[:,np.newaxis].shape)
print()
print()
print(a[np.newaxis,:])
print()
print()
print(a[np.newaxis,:].shape)

In [ ]:
import numpy as np 
a=np.array((1,2,3))
a

In [ ]:
import numpy as np
x=np.linspace(0,75,num=6,retstep=True)
print(x)

In [ ]:
6*60

## TASK

#### Which among the following will produce the same result as:
1. np.linspace(1,10,10,dtype='int32')
2. np.arange(1,11)
3. np.random.randint(1,11)
4. np.array(range(1,11))

In [ ]:
print(np.linspace(1,10,10,dtype='int32'))
print()
print(np.arange(1,11))
print()
print(np.random.randint(1,11))
print()
print(np.array(range(1,11)))

### Conversion and other function

In [ ]:
#Converting a 1-D array to a 2-D array using reshape() 
#Returns an array containing the same data with a new shape.
arr_co1=np.linspace(20,30,6,dtype='int32')
print(arr_co1.reshape(6))#(2,3)
print(arr_co1.reshape(2,3))#(2,3)
print()
print()
x=np.random.randint(5,10,(2,3))
print(x)
print()
y=x.reshape(3,2)
print(y)

In [ ]:
arr_co2=np.arange(20).reshape(2,10)
#arr_co2=np.arange(1,21).reshape(2,10)
print(arr_co2)
print(arr_co2.max())#axis=None is default gives max value
print(arr_co2.min())# gives min value
print(arr_co2.argmax())# gives the value at which maximum value from the function is attend
print(arr_co2.argmin())# gives the value at which minimum value from the function is attend

In [ ]:
a=np.random.randint(10,100,(2,3))# Creates a 2 by 3 matrix of values between 10 and 1000
print(a)
print()
print()
print(a.max(axis=1))#axis=0/1(row)
print()
print()
print(a.min(axis=0))# columnwise
print()
print()
print(a.argmax(axis=1)) #
print()
print()
print(a.argmax(axis=0))#

### Practice Work

### Write a NumPy program to test whether none of the elements of a given array is zero.

### Write a NumPy program to test if any of the elements of a given array is non-zero

### Write a NumPy program to generate five random numbers from the normal distribution.

### Write a NumPy program to generate six random integers between 10 and 30.

### Write a NumPy program to get the numpy version and show numpy build configuration.

### Write a NumPy program to  get help on the add function.

### create Numpy Array

To create a NumPy array we need to pass list of element values inside a square bracket as an argument to the np.array() function.

In [ ]:
### A 3d array is a matrix of 2d array. 
### A 3d array can also be called as a list of lists where every element is again a list of elements.

import numpy as np 
ar1=np.array([1,2,3,4,5])
ar2=np.array([[1,2,3],[4,5,6]])
ar3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(ar1)
print("-"*10)
print(ar2)
print("-"*10)
print(ar3)

**Shape:**	A tuple that specifies the number of elements for each dimension of the array.<br>
**Size:**	The total number elements in the array.<br>
**Ndim:**	Determines the dimension an array.<br>
**nbytes:**	Number of bytes used to store the data.<br>
**dtype:**	Determines the datatype of elements stored in array.<br>

Data Types Supported by NumPy
The dtype method determines the datatype of elements stored in NumPy array. You can also explicitly define the data type using the dtype option as an argument of array function.

dtype	    |            Variants                |  Description
------------|------------------------------------|-------------------------
int	        | int8, int16, int32, int64          |  Integers
uint        | uint8, uint16, uint32, uint64	     |  Unsigned (nonnegative) integers
bool        | Bool	                             |  Boolean (True or False)
code>float  | float16, float32, float64, float128|  Floating-point numbers
complex	    | complex64, complex128, complex256  |  Complex-valued floating-point numbers

# Numeric data manipulation, taublar dataframe and data visualization

### Core features of numpy
We will start by looking at the api to create arrays, delete array, access element of arrays, delete element of arrays.

### Arrays creation
Arrays can be created in different ways. Here are some examples:

In [ ]:
# create an array from an existing list, tuple or generator
l = [1, 2, 3]
t = [4, 5, 6]
g = range(7, 10)

a = np.array(l); print(a)
a = np.array(t); print(a)
a = np.array(g); print(a)

In [ ]:
%%writefile array_data.txt
# this is a comment in the file
x, y, z
1, 2, 3
1, 4, 5
2, 3, 5

In [ ]:
# read from txt file with comments and headers
w = np.genfromtxt('array_data.txt',  # filename
                        skip_header=2,  # number of rows to skip
                        delimiter=',', #type of value separator
                        unpack=True) # columns into single variables
print('Data read from .txt file')
print(x); print(y); print(z)

In [ ]:
# generate array from a particular function
a = np.arange(0, 1, 0.1) # from 0 to 1 with 0.1 steps
# print(a)
b = np.linspace(0, 5, 10) # from 0 to 5 such that there are 10 elements
# print(b)
c = np.empty(10) # 10 elements with random values inside
# print(c)
d = np.zeros(10) # 10 elements with 0s inside
# print(d)
e = np.full_like(d, 3) # array big like d but with 3 elements inside
# print(e)
f = np.random.random(10)  # array of random elements
# print(f)

## Accessing elements of arrays

Accessing elements of array is similar to python syntax for lists but it can be extended to a more powerful behaviour

In [ ]:
a = np.arange(5, 15)  # 10 elements from 5 to 15 excluded
a

In [ ]:
first = a[0]  # access the first element
last = a[-1]  # access the last element
slice1 = a[:4] # access element from 0 to 4 excluded (0, 1, 2, 3)
slice2 = a[1:3] # access elements from 1 included to 3 excluded (1, 2)
slice3 = a[-3:-1]  # access element from the third last included to the last exclued (-3, -2)
slice4 = a[4:]  # access elements from 4 included until the end
slice5 = a[1:8:2]  # access from 1 inclued to 8 excluded with steps of 2 (1, 3, 5, 7)
slice6 = a[::3] # access every third element (0, 3, 6, 9)
# bonus: reverse an array
slice7 = a[::-1]

In [ ]:
a

In [ ]:
mask = a > 8
mask

In [ ]:
# more indexing methods
submask = [1, 3, 7, 9] 
slice8 = a[submask]  # access the elements in the positions described by submask

# boolean indexing.
mask = a > 8  # mask is a variable of booleans
print(mask)
slice9 = a[mask]  # a boolean maks can be used to select only certain element
slice10 = a[a > 8]  # alternative syntax

print(slice9, slice10)

## Some interesting numpy functions

### Math functions
numpy has a fairly big set of functions to for mathematical operations

In [ ]:
# standard math functions, like mean, standard deviations, max, min, etc. 
# are all available
a = np.array([10, 8, 9])
print('Mean: ', np.mean(a))
print('Standard deviation: ', np.std(a))
print('Max: ', np.max(a))
print('Min: ', np.min(a))
print('Ix Max: ', np.argmax(a))
print('Ix Min: ', np.argmin(a))

### Inserting and deleting elements

numpy are blocks of memory with a different layout than the list. For this reason it's not possible to append and element like a list, thoug similar functions are provided

In [ ]:
a = np.array([1, 2, 3])

b = np.append(a, 3); print(b) # insert the number 3 at the end
c = np.insert(a, 2, 12); print(c)  # insert the value 12 at index 2
d = np.delete(a, 1); print(d) # delete the value at index 1

## Vectorization and broadcasting

These following two concepts are probably the most powerful concepts used in numpy. Sometimes they're used without we notice it. Let's consider the following examples

In [ ]:
a = np.array([1, 2, 3])

# I want the square of each element: there is the dedicated function
print(np.square(a))
# I want each element to the power of 6 for example:
print(np.power(a, 6)); print(a ** 6)
# I want to divide each element by 3
print(a / 3)
# I want to subtract 2 from each element
print(a - 2)

The operations between an array/vector and a scalar value are possible because numpy can smartly understand the dimension of both variables and apply the operator to each value of the first element using the value of the second.

In [ ]:
x = np.array([1, 1, 3])
y = np.array([2, 3, 3])

# I  want to mulitply each element of x by the correspndding element of y
print(x * y)

So if there are two array with the same dimension (1d in this case) the operation are applied element-wise. If there is a 1d array and a scalar then the scalr is applied to each element of the array.

## Multi dimensional array

Sometimes we want to work with n-dimensional arrays. Let's see some examples

In [ ]:
# Create a 2d array 2x2 of random elements
m = np.random.random((2, 2))
m

In [ ]:
# create a 4x6 array of elements from 1 to 24
m = np.arange(1, 25)
print(m)
m = m.reshape((4, 6))
m

In [ ]:
# example of error: 25 elements are not divisible by 4 so 
# I can't create a matrix of 4 rows
m = np.arange(0, 25)
m = m.reshape((4, 6))

In [ ]:
# sometimes we only need to reshape an array knowing the number of rows 
# but we don't know the number od columns (or viceversa). In this case
# we can use -1 in the reshape function
m = np.arange(0, 60)
reshape1 = m.reshape((-1, 2)) # it will create a 30x2
reshape2 = m.reshape((2, -1)) # it will create a 2x30
reshape3 = m.reshape((2, 6, -1)) # it will create a 2x6x5
print(reshape3)

## The axis arguments

some numpy functions accepts an `axis` argument. This is used in multidimensional array to apply the operation over a particular axis. Let's see a simple example:

**School grades**
There three students attending the physics class. Their marks over time are saved into a simple .txt file

In [ ]:
%%writefile school_grades.txt
tizio, caio, sempronio
9, 9, 10
8, 6, 9
10, 9, 9
7, 7, 8

In [ ]:
# read the data into a single array
grades = np.genfromtxt('school_grades.txt', skip_header=1, delimiter=',')
grades

In [ ]:
# the shape of the array is 
grades.shape

In [ ]:
# I want the global average mark for each student
mean_marks_per_student = np.mean(grades, axis=0)
mean_marks_per_student

In [ ]:
# I want the average mark between the students for each test
mean_marks_per_test = np.mean(grades, axis=1)
mean_marks_per_test

So the array has a *4* rows and *3* columns. The shape can be accessed by the attribute `grades.shape` and returns a tuple `(nrows, ncolumns)`. The axis argument can be used to apply a function over an axis and it works this way:

* If the axis is 0 it will collpase the axis at the 0-th position in the shape of the array. This means from `(nrows, ncolumns)` -> `(ncolumns)`
* If the axis is 1 it will collapse the axis at the 1-st position in the shape of the array. This means that `(nrows, ncolumns)` -> `(nrows)`
* In general if we have an array of the shape `(s1, s2, s3, ...)` the axis is an integer number (or a tuple) from 0 to `ndim-1`. The number specified in the `axis` arguments will be the dimensions the will collapse.

```
a = np.array([...])
a.shape = (s1, s2, s3, s4)
           0,  1,  2,  3
           
np.mean(a, axis=0) -> (s2, s3, s4)
np.mean(a, axis=(0, 1)) -> (s3, s4)
np.mean(a, axis=3) -> (s1, s2, s3)
```

In [ ]:
a = np.random.random(420)
print(a.shape)
a = a.reshape((2, 3, 2, 5, 7))
#              0, 1, 2, 3, 4
print(a.shape)

print(a.mean(axis=1).shape) # 0, 2, 3, 4
print(a.mean(axis=0).shape) # 1, 2, 3, 4
print(a.mean(axis=(2, 3)).shape) # 0, 1, 4
print(a.mean(axis=-1).shape) # 0, 1, 2, 3

<h1 style="color:green" align='center'>Numpy tutorial: iterate numpy array using nditer</h1>

In [ ]:
import numpy as np

In [ ]:
a = np.arange(12).reshape(3,4)
a

<h3 style="color:purple">Using normal for loop iteration</h3>

In [ ]:
for row in a:
    for cell in row:
        print(cell)

<h3 style="color:purple">For loop with flatten</h3>

In [ ]:
for cell in a.flatten():
    print(cell)

<h1 style="color:blue" align="center">nditer</h1>

In [ ]:
for x in np.nditer(a, order='C'):
    print(x)

<h2 style="color:purple">Fortan style ordering</h2>

In [ ]:
for x in np.nditer(a, order='F'):
    print(x)

<h3 style="color:purple">external_loop</h3>

In [ ]:
for x in np.nditer(a, flags=['external_loop'],order='F'):
    print(x)

<h2 style="color:purple">Modify array values while iterating</h2>

In [ ]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

In [ ]:
a

<h2 style="color:purple">Iterate two broadcastable arrays concurrently</h2>

In [ ]:
b = np.arange(3, 15, 4).reshape(3,1)
b

In [ ]:
for x, y in np.nditer([a,b]):
    print (x,y)

### tutorial

In [ ]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])


In [ ]:
import numpy as np
import time
import sys
SIZE = 1000000
l1 = range(SIZE)
l2 = range(SIZE)
a1=np.arange(SIZE)
a2=np.arange(SIZE)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ",(time.time()-start)*1000)
# numpy array
start= time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start)*1000)

# Linear algebra with Numpy

It is possible to do symbolic linear algebrea with [Sympy](http://www.sympy.org/en/index.html) but for numeric computations [Numpy](http://www.numpy.org/) is a high performance library that should be used. 

Here is how it is described: 

> NumPy is the fundamental package for scientific computing with Python. It contains among other things: [...]
 useful linear algebra, Fourier transform, and random number capabilities.

In this section we will see how to:

- Manipulate matrices;
- Solve Matrix equations;
- Calculate Matrix inverse and determinants.

## Manipulating matrices

It is straightforward to create a Matrix using Numpy. Let us consider the following as a examples:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
B = \begin{pmatrix}
14 & -2 & 12\\
4 & 4 & 5\\
5 & 5 & 1
\end{pmatrix}
$$


First, similarly to Sympy, we need to import Numpy:

In [ ]:
import numpy as np

Now we can define A:

In [ ]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
A

In [ ]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])
B

We can obtain the following straightforwardly:

- **5A** (or any other scalar multiple of **A**);
- **A ^ 3** (or any other exponent of **A**);
- **A + B**;
- **A - B**;
- **AB**

In [ ]:
5 * A

In [ ]:
A ** 3

In [ ]:
A + B

In [ ]:
A - B

In [ ]:
A * B

---

**EXERCISE** Compute $A ^ 2 - 2 A + 3$ with:

$$A = 
\begin{pmatrix}
1 & -1\\
2 & 1
\end{pmatrix}
$$

---

## Solving Matrix equations

We can use Numpy to (efficiently) solve large systems of equations of the form:

$$Ax=b$$

Let us illustrate that with:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
b = \begin{pmatrix}
-1\\
2\\
1 
\end{pmatrix}
$$

In [ ]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

We use the `linalg.solve` command:

In [ ]:
x = np.linalg.solve(A, b)
x

We can verify our result:

In [ ]:
A * x

---

**EXERCISE** Compute the solutions to the matrix equation $Bx=b$ (using the $B$ defined earlier).

---

## Matrix inversion and determinants

Computing the inverse of a matrix is straightforward:

In [ ]:
Ainv = np.linalg.inv(A)
Ainv

We can verify that $A^{-1}A=\mathbb{1}$:

In [ ]:
A * Ainv

The above might not look like the identity matrix but if you look closer you see that the diagonals are all `1` and the off diagonals are a **very** small number (which from a computer's point of view is `0`).

To calculate the determinant:

In [ ]:
np.linalg.det(A)

---

**EXERCISE** Compute the inverse and determinant of $B$ (defined previously).

---

## Summary

In this section we have seen how to using Numpy:

- Manipulate matrices;
- Solve linear systems;
- Compute Matrix inverses and determinants.

This again just touches on the capabilities of Numpy.

Let us take a look at [Pandas](03 - Data analysis with Pandas.ipynb) for data analysis.

## Source(s): 
* https://numpy.org/devdocs/user/quickstart.html
* https://www.tutorialspoint.com/numpy/index.htm